/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AceitarConviteTokenRouteImport } from './routes/aceitar-convite.$token'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedOrdensRouteImport } from './routes/_authenticated/ordens'
import { Route as AuthenticatedGarantiasRouteImport } from './routes/_authenticated/garantias'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAparelhosRouteImport } from './routes/_authenticated/aparelhos'
import { Route as AuthenticatedOrdensIdRouteImport } from './routes/_authenticated/ordens_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteTokenRoute = AceitarConviteTokenRouteImport.update({
  id: '/aceitar-convite/$token',
  path: '/aceitar-convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdensRoute = AuthenticatedOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGarantiasRoute = AuthenticatedGarantiasRouteImport.update({
  id: '/garantias',
  path: '/garantias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAparelhosRoute = AuthenticatedAparelhosRouteImport.update({
  id: '/aparelhos',
  path: '/aparelhos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdensIdRoute = AuthenticatedOrdensIdRouteImport.update({
  id: '/ordens_/$id',
  path: '/ordens/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aparelhos': typeof AuthenticatedAparelhosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/garantias': typeof AuthenticatedGarantiasRoute
  '/ordens': typeof AuthenticatedOrdensRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/aceitar-convite/$token': typeof AceitarConviteTokenRoute
  '/ordens/$id': typeof AuthenticatedOrdensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aparelhos': typeof AuthenticatedAparelhosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/garantias': typeof AuthenticatedGarantiasRoute
  '/ordens': typeof AuthenticatedOrdensRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/aceitar-convite/$token': typeof AceitarConviteTokenRoute
  '/ordens/$id': typeof AuthenticatedOrdensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/aparelhos': typeof AuthenticatedAparelhosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/garantias': typeof AuthenticatedGarantiasRoute
  '/_authenticated/ordens': typeof AuthenticatedOrdensRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/aceitar-convite/$token': typeof AceitarConviteTokenRoute
  '/_authenticated/ordens_/$id': typeof AuthenticatedOrdensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/aparelhos'
    | '/dashboard'
    | '/financeiro'
    | '/garantias'
    | '/ordens'
    | '/perfil'
    | '/aceitar-convite/$token'
    | '/ordens/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/aparelhos'
    | '/dashboard'
    | '/financeiro'
    | '/garantias'
    | '/ordens'
    | '/perfil'
    | '/aceitar-convite/$token'
    | '/ordens/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/aparelhos'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/garantias'
    | '/_authenticated/ordens'
    | '/_authenticated/perfil'
    | '/aceitar-convite/$token'
    | '/_authenticated/ordens_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AceitarConviteTokenRoute: typeof AceitarConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite/$token': {
      id: '/aceitar-convite/$token'
      path: '/aceitar-convite/$token'
      fullPath: '/aceitar-convite/$token'
      preLoaderRoute: typeof AceitarConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ordens': {
      id: '/_authenticated/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof AuthenticatedOrdensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garantias': {
      id: '/_authenticated/garantias'
      path: '/garantias'
      fullPath: '/garantias'
      preLoaderRoute: typeof AuthenticatedGarantiasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aparelhos': {
      id: '/_authenticated/aparelhos'
      path: '/aparelhos'
      fullPath: '/aparelhos'
      preLoaderRoute: typeof AuthenticatedAparelhosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ordens_/$id': {
      id: '/_authenticated/ordens_/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AuthenticatedOrdensIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAparelhosRoute: typeof AuthenticatedAparelhosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedGarantiasRoute: typeof AuthenticatedGarantiasRoute
  AuthenticatedOrdensRoute: typeof AuthenticatedOrdensRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedOrdensIdRoute: typeof AuthenticatedOrdensIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAparelhosRoute: AuthenticatedAparelhosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedGarantiasRoute: AuthenticatedGarantiasRoute,
  AuthenticatedOrdensRoute: AuthenticatedOrdensRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedOrdensIdRoute: AuthenticatedOrdensIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AceitarConviteTokenRoute: AceitarConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
